trigger:
      - master

jobs:
  - job: buildjob
    displayName: Build Job
    variables:
      buildConfiguration: 'Release'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '9.0.x'

      - script: |
          dotnet build --configuration $(buildConfiguration)
        displayName: 'dotnet build $(buildConfiguration)'