trigger:
  branches:
    include:
      - master

stages:
- stage: Teste
  jobs:
  - job: Exemplo
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo "Pipeline executando com sucesso"
      displayName: "Etapa de validação"