trigger:
  branches:
    include:
      - master
      - dev
      - hml
      - prd

pool:
  name: BuildStorePipeline   

variables:
  solution: 'BuildStoreEnterprise.sln'
  dotnetVersion: '9.0.x'
  buildConfiguration: 'Release'

steps:
- checkout: self

- task: UseDotNet@2
  displayName: 'Instalar .NET SDK $(dotnetVersion)'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build da solução'