trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- script: dotnet build BuildStoreEnterprise.sln --configuration Release
  displayName: 'Build da solução'