trigger:
  branches:
    include:
      - master

pool:
  name: BuildStorePipeline   

steps:
- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build da solução'